config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "posts#index"
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post  
  validates :body, presence: true;
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, uniqueness:{ case_sensitive: false}
    validates :body, presence: true, length:{minimum:50}
    has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post

    def create
        @comment =Comment.new comment_params
        @comment.post=@post
        @comment.save 
        redirect_to post_path(@post), notice: "Comment created"          
    end

    def destroy
        @comment = Comment.find params[:id]
        @comment.destroy
        redirect_to post_path(@post), notice: "Comment deleted"  
    end


    private
    def find_post
        @post = @post = Post.find_by_id params[:post_id]
    end

    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :find_post, only:[:show, :edit, :update, :destroy]
    def new
        @post = Post.new
    end


    def create
        @post = Post.new post_params

        if @post.save
            flash[:notice]="Post created successfully"
            redirect_to post_path(@post.id)
        else
            render :new
        end
    end


    def index
        @posts = Post.all.order(created_at: :desc)
        
    end

    def show
        #byebug
        @comments = @post.comments.order(created_at: :DESC)
        @comment = Comment.new
    end

    def edit
     
    end

    def update
            if @post.update post_params
                redirect_to post_path(@post.id), notice: "Post edited"
            else
                render :edit
            end
    end

    def destroy
        if @post.destroy
            flash[:notice] = "The  post #{@post.title} has been destroyed"
            redirect_to posts_path
        else
            render :show
        end
    end


    private
    def post_params
        params.require(:post).permit(:title, :body)
    end

    def find_post
        @post = Post.find_by_id params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    
    <%= render"/shared/navbar"%>
    <%= render"/shared/alert"%>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= render"shared/form.html.erb"%>

app/views/posts/index.html.erb
<div class="container">
<div class="row">

<% @posts.each do |post|%>
<div class="card col-xs-11 col-sm-11 col-md-5 col-lg-3 col-xlg-3 m-4">
    <div class="card-body">
    <h2><%= link_to(post.title, post_path(post.id))%></h2>
    <p><%= post.body%></p>
    </div>
</div>
<%end%>

</div>
</div>

app/views/posts/new.html.erb
<%= render"shared/form.html.erb"%>

app/views/posts/show.html.erb
<div class="container">
    <h1><%= @post.title%></h1>
    <p><%= @post.body%></p>
    <p>Posted <%= time_ago_in_words(@post.created_at)%> ago</p>

    <div>
    <%= link_to("Edit", edit_post_path(@post.id), class:"btn btn-outline-primary")%>
    <%= link_to("Delete", post_path(@post.id), method: :delete, class:"btn btn-outline-primary")%>
    </div>

      <div class="mt-4">
        <%= form_with model: [@post, @comment], :class=>"form-group", local:true do |f|%>
            <h4><%= f.label:comment%></h4>
            <div class="input-group mb-2">
                <%= f.text_area:body,cols:90,rows:5,  placeholder: "What's on your mind?",  :class=>'form-control', :required=>true%>
            </div>
            <div>
                <%= f.submit :Submit, class:"btn btn-outline-primary"%>
            </div>
        <%end%>

    </div>

        <% @comments.each do |comment|%>
     
            <p class="d-flex flex-column mt-4"><%= comment.body%>
            <small>Commented <%= time_ago_in_words(comment.created_at)%> ago • &nbsp;
            <%= link_to("Delete", post_comment_path(@post.id, comment.id), method: :delete)%></small></span>
             </p>
    <%end%>
</div>

app/views/posts/show_1.html.erb
<div class="container">
    <h1><%= @post.title%></h1>
    <p><%= @post.body%></p>
    <p>Posted <%= time_ago_in_words(@post.created_at)%> ago</p>

    <div>
    <%= link_to("Edit", edit_post_path(@post.id), class:"btn btn-outline-primary")%>
    <%= link_to("Delete", post_path(@post.id), method: :delete, class:"btn btn-outline-primary")%>
    </div>

    <div class="mt-4">
        <%= form_with model: [@post, @comment], :class=>"form-group", local:true do |f|%>
            <h4><%= f.label:comment%></h4>
            <div class="input-group mb-2">
                <%= f.text_area:body,cols:90,rows:5,  placeholder: "What's on your mind?",  :class=>'form-control', :required=>true%>
            </div>
            <div>
                <%= f.submit :Submit, class:"btn btn-outline-primary"%>
            </div>
        <%end%>

    </div>

        <% @comments.each do |comment|%>
     
            <p class="d-flex flex-column mt-4"><%= comment.body%>
            <small>Commented <%= time_ago_in_words(comment.created_at)%> ago • &nbsp;
            <%= link_to("Delete", post_comment_path(@post.id, comment.id), method: :delete)%></small></span>
             </p>
    <%end%>
</div>

app/views/shared/_alert.html.erb
<% if flash[:notice].present?%>
<div class="alert alert-success alert-dismissable fade show" role="alert">
    <%= flash[:notice]%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>

<% elsif flash[:alert].present?%>
<div class="alert alert-warning alert-dismissable fade show" role="alert">
    <%= flash[:alert]%>
    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>  

app/views/shared/_form.html.erb
<div class="container mt-4">
<%= form_with model: @post, :class=>"form-group", local:true do |f|%>
    <%if @post.errors.any?%>
        <p><%= @post.errors.full_messages.join(", ")%></p>
    <%end%>
    <%= f.label :title%>
    <div class="input-group">
        
        <%= f.text_field :title, :class=>'form-control', :required=>true%>
    </div>
    <%= f.label :body%>
    <div class="input-group">
        
        <%= f.text_area :body, cols:50 , rows:5,  :class=>'form-control', :required=>true %>
    </div>
        <%= f.submit :class => 'btn btn-outline-primary mt-4'%>
<%end%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
<div class="navbar-brand">
    <%= link_to("Blog On Rails", root_path)%>
</div>
<div>
<%= link_to("Home", root_path)%>
|
<%= link_to("New Post", new_post_path)%>
</div>
</nav>